- .ado/build-dll.yml
- config.json
- localbuild.ps1
- scripts/Install-VSFeatures.ps1
- scripts/patch/build.diff
- scripts/patch/src.diff
- src/BUILD.gn
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/V8Platform.cpp
- src/V8Platform.h
- src/inspector/inspector_agent.cpp
- src/inspector/inspector_socket.cpp
- src/public/V8JsiRuntime.h
- Fix a couple of bugs around the inspector (crash on detach, hang on shutdown with debugger attached, etc.);
- Upgrade to V8 version 8.4;
> Fix basic debugging support. Upgrade to V8 8.4

- android/BUILD.gn
- android/FileUtils.cpp
- android/FileUtils.h
- android/V8Platform.cpp
- android/V8Platform.h
- android/V8Runtime.h
- android/V8Runtime_basic.cpp
- android/V8Runtime_droid.cpp
- android/V8Runtime_impl.h
- android/V8Runtime_shared.cpp
- android/jsi/CMakeLists.txt
- android/jsi/JSIDynamic.cpp
- android/jsi/JSIDynamic.h
- android/jsi/decorator.h
- android/jsi/instrumentation.h
- android/jsi/jsi-inl.h
- android/jsi/jsi.cpp
- android/jsi/jsi.h
- android/jsi/jsilib-posix.cpp
- android/jsi/jsilib-windows.cpp
- android/jsi/jsilib.h
- android/jsi/test/testlib.cpp
- android/jsi/test/testlib.h
- android/jsi/threadsafe.h
- android/scripts/build.patch
- android/scripts/build.sh
- android/scripts/src.patch
- android/version-script/makev8jsi.lst
For the first version, we have taken the JSI glue code out of our react native fork. The code of this code is mostly identical to our windows code now, but as we've added a bunch of code to Windows version after we forked off, it won't be a trivial exercise to unify the code. But, keeping both code in the same repo will make our life easier in the future to consolidate both.
A bunch of code cleanup is planned which i'd like to do in subsequent iterations.
> Building v8jsi binary for Android. 

- .ado/build-dll.yml
- azure-pipelines-uwp.yml
- azure-pipelines.yml
- config.json
- scripts/build.ps1
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/jsi/jsi.h
- src/jsi/test/testlib.cpp
- Fix V8 JSI implementation enough to pass (most) unit tests;
- Add a Test step to CI;
- Build and include windbg extension (for win32 x86/x64);
> Fix JSI implementation to pass unit tests. Include windbg extension

- .ado/build-dll.yml
- .ado/pull-request.yml
- ReactNative.V8Jsi.Windows.nuspec
- azure-pipelines-uwp.yml
- azure-pipelines.yml
Add common PR file `.ado/pull-request.yml`.
Note, a test [build definition](https://dev.azure.com/ms/v8-jsi/_build?definitionId=428) was set up to validate this PR.
After merge, the current PR build definition will be re-routed to `.ado/pull-request.yml`.
> Consolidate pull request CI logic.

- config.json
- scripts/patch/src.diff
- src/BUILD.gn
> Update V8 to v8.7

- .ado/pull-request.yml
- scripts/fetch_code.ps1
- Copies `ReactNative.V8Jsi.Windows.nuspec` to the output directory for artifact publishing.
- Fails if no NUPKG file gets created.
> Fix nuget pack

- config.json
Trigger building version `0.64.6`.
> Bump version to 0.64.6

- .ado/pull-request.yml
- config.json
> Include PDBs in the win32 NuGet to match prior behavior

- config.json
- scripts/patch/build.diff
- scripts/patch/src.diff
> Update V8 to 8.9

- config.json
- scripts/patch/build.diff
- scripts/patch/src.diff
> Update to V8 version 8.9 (backport to 0.63)

- .clang-format
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/V8Platform.cpp
- src/V8Platform.h
- src/etw/tracing.cpp
- src/etw/tracing.h
- src/public/ScriptStore.h
- src/public/V8JsiRuntime.h
- src/testmain.cpp
Last few PRs have a lot of code changes mostly because we had to auto-format the code.
In this PR we format existing code files and set the Clang format ColumnLimit to 120 as in the react-native-windows projects.
It would be ideal if this PR is merged before the other two outstanding PRs to reduce number of changed lines in these PRs.
There are no code changes in PR besides the auto-formatting and fixing some spelling issues in a few comments.
> Set Clang format ColumnLimit to 120

- src/IsolateData.h
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/inspector/inspector_agent.cpp
- src/inspector/inspector_agent.h
- src/inspector/inspector_socket_server.cpp
- src/napi/js_native_ext_api_v8.cpp
- src/public/V8JsiRuntime.h
This removes unused fields and simplifies the V8RuntimeArgs struct.
> Clean up arguments

- config.json
- scripts/build.ps1
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/napi/js_native_ext_api_v8.cpp
- src/public/V8JsiRuntime.h
> Backport argument cleanup from master

- config.json
- src/IsolateData.h
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/inspector/inspector_agent.cpp
- src/inspector/inspector_agent.h
- src/inspector/inspector_socket_server.cpp
- src/inspector/inspector_socket_server.h
- src/public/V8JsiRuntime.h
> Backport latest changes from mater

- .ado/pull-request.yml
- ReactNative.V8Jsi.Windows.nuspec
> Filter NuGet content by platform to avoid exceeding size limit

- .ado/pull-request.yml
- ReactNative.V8Jsi.Windows.nuspec
- config.json
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/inspector/inspector_agent.cpp
- src/inspector/inspector_agent.h
- src/inspector/inspector_socket.cpp
- src/inspector/inspector_socket_server.cpp
- src/inspector/inspector_socket_server.h
- src/inspector/inspector_tcp.cpp
Backport recent changes from master, including:
* V8 9.3
* Fix in inspector code at shutdown
* Fix for folder layout in NuGet
> [0.63] Backport

- config.json
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/jsi/decorator.h
- src/jsi/jsi.h
- src/public/NapiJsiRuntime.cpp
See https://github.com/microsoft/react-native-windows/blob/0748834a41d71a5e3f70dfc83d0a005a83b4e8a2/vnext/package.json#L75
Updates src\jsi\jsi.h to React Native 4ad4426daf51903574f81aff1b773645a16831e0.
- Must be backported to `0.64-stable`.
> Update src\jsi\jsi.h to rn@4ad4426da

- config.json
- src/V8JsiRuntime.cpp
- src/napi/js_native_ext_api_v8.cpp
- src/public/V8JsiRuntime.h
- src/public/js_native_ext_api.h
> Add a flag for enabling built-in V8 ETW instrumentation

- config.json
- scripts/patch/src.diff
> Update to V8 9.4

- config.json
- scripts/patch/src.diff
> [0.63] Update to V8 9.4

- config.json
- scripts/patch/src.diff
> [0.64] Update to V8 9.4

- config.json
- scripts/patch/src.diff
- src/inspector/inspector_agent.cpp
See https://v8.dev/blog/v8-release-95.
> Upgrade V8 to version 9.5

- config.json
- scripts/patch/src.diff
- src/inspector/inspector_agent.cpp
> [0.64] Upgrade V8 to version 9.5

- config.json
- scripts/patch/src.diff
- src/inspector/inspector_agent.cpp
> [0.63] Upgrade V8 to version 9.5

- config.json
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/inspector/inspector_socket_server.cpp
- src/inspector/inspector_socket_server.h
> [0.64] Update to V8 9.7

- config.json
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/inspector/inspector_socket_server.cpp
- src/inspector/inspector_socket_server.h
> [0.63] Update to V8 9.7

- config.json
- src/V8JsiRuntime.cpp
- src/inspector/inspector_socket_server.cpp
Backport recent changes in the master branch.
> [0.64] Backport from master

- .ado/build-dll.yml
- .ado/pull-request.yml
- config.json
- scripts/build.ps1
- scripts/fetch_code.ps1
- src/V8JsiRuntime.cpp
Make sure globalInitializeTracing is only called once
Also port misc changes from master
> Call globalInitializeTracing only once

- .ado/android-build.yml
- .ado/build-dll.yml
> Add SBom Generation

- .ado/android-ci.yml
- .ado/android-pr.yml
> Fix typo in android pipeline

- config.json
- scripts/fetch_code.ps1
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/public/NapiJsiRuntime.cpp
- src/public/compat.h
Google switched to using C++17 for this release, so we can clean up some of the compat code as well (string_view native).
> Update to V8 9.9

- .ado/android-build.yml
- .ado/android-ci.yml
- .ado/android-jobs.yml
- .ado/windows-build.yml
- .ado/windows-jobs.yml
- GuardianCustomConfiguration.json
> Make publish pipeline compliant

- android/scripts/build.sh
- scripts/fetch_code.ps1
Remove some of the code not used during builds that is tripping out the compliance checks.
> Remove unused code

- README.md
- android/scripts/build.sh
- scripts/fetch_code.ps1
Remove additional directories that are not needed for the actual build.
> More dependency cleanup

- .ado/windows-build.yml
- .ado/windows-jobs.yml
- README.md
- config.json
- localbuild.ps1
- scripts/build.ps1
- scripts/download_depottools.ps1
- scripts/fetch_code.ps1
- scripts/patch/src.diff
- src/BUILD.gn
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/V8Windows.h
- src/etw/tracing.cpp
- src/etw/tracing.h
- src/makev8jsi.lst
- src/napi/js_native_ext_api_v8.cpp
- src/public/NapiJsiRuntime.h
- src/public/V8JsiRuntime.h
- src/testmain.cpp
- Refactor / clean up build scripts (should improve build speed by 5%+)
- Add experimental support for building on/for Android, Linux and Mac with the same PowerShell build script
> Build improvements

- src/MurmurHash.cpp
- src/MurmurHash.h
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/napi/js_native_ext_api_v8.cpp
- src/public/NapiJsiRuntime.h
- src/public/V8JsiRuntime.h
- src/public/js_native_ext_api.h
In this PR we format code in a few selected source files.
These are either new files or the files that I plan to change in the next PR.
The goal is to reduce unnecessary changes in the follow up PRs.
There are no other code changes except for "modernizing" `Microsoft::JSI` namespace in NapiJsiRuntime.h.
> [0.65] Format code

- src/MurmurHash.cpp
- src/MurmurHash.h
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/napi/js_native_ext_api_v8.cpp
- src/public/V8JsiRuntime.h
- src/public/js_native_ext_api.h
In this PR we format code in a few selected source files.
These are either new files or the files that I plan to change in the next PR.
The goal is to reduce unnecessary changes in the follow up PRs.
There are no other code changes.
> Format code

- .gitignore
- config.json
- scripts/fetch_code.ps1
- scripts/patch/build.diff
- scripts/patch/src.diff
- src/BUILD.gn
- src/V8JsiRuntime.cpp
- src/napi/test/js-native-api/test_exception/test_exception.c
- src/source_link.json
- Update to the 10.3 version of V8;
- Initial implementation of source links (note that this doesn't include our patched files);
> Update to V8 10.3

- .ado/android-build.yml
> Ignore "android/build/v8/third_party/depot_tools" for Component Governance.

- config.json
- scripts/patch/src.diff
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/inspector/inspector_agent.cpp
> Update to V8 10.6

- config.json
- src/V8JsiRuntime.cpp
> Clear any unhandled promise rejection while the runtime is still alive

- config.json
- src/V8JsiRuntime.cpp
> [0.65] Clear any unhandled promise rejection while the runtime is still alive

- config.json
- src/V8JsiRuntime.cpp
- src/V8JsiRuntime_impl.h
- src/napi/js_native_api_v8.h
- src/napi/js_native_ext_api_v8.cpp
- src/public/V8JsiRuntime.h
- src/public/js_native_ext_api.h
- src/testmain.cpp
> Multi threaded support

- config.json
- scripts/build.ps1
- scripts/fetch_code.ps1
- scripts/patch/src.diff
- src/BUILD.gn
> [0.69] Update to V8 10.9

- config.json
- scripts/build.ps1
- scripts/fetch_code.ps1
- scripts/patch/src.diff
- src/BUILD.gn
> [0.70] Update to V8 10.9

- config.json
Update v8jsi version to 0.71.7
> Update v8jsi version to 0.71.7

- config.json
- scripts/patch/src.diff
- src/inspector/inspector_socket_server.h
- src/jsi/test/testlib.cpp
- src/napi/test/js-native-api/common.c
- src/napi/test/js-native-api/common.h
- src/node-api-jsi/NodeApiJsiRuntime.cpp
Note: this wasn't validated against Office yet due to pending API changes.
> Update to V8 11.8

- ReactNative.V8Jsi.Windows.nuspec
- config.json
- src/jsi/CMakeLists.txt
- src/jsi/jsi.h
- src/node-api-jsi/ApiLoaders/JSRuntimeApi.cpp
- src/node-api-jsi/NodeApiJsiRuntime.cpp
- src/node-api-jsi/NodeApiJsiRuntime.h
- src/node-api/js_runtime_api.h
Bring in updated headers from microsoft/node-api-jsi
Also fix a small mistake in the .nuspec
> Bring in updated headers from microsoft/node-api-jsi

- .ado/windows-jobs.yml
> Job names cannot have spaces or symbols other than _ in them

- .ado/windows-build.yml
- .ado/windows-ci.yml
- .ado/windows-jobs.yml
- .ado/windows-pr.yml
- config.json
- scripts/fetch_code.ps1
- scripts/patch/build.diff
- scripts/patch/src.diff
- scripts/update_version.ps1
- src/V8JsiRuntime.cpp
- src/node-api-jsi/NodeApiJsiRuntime.cpp
This includes the update to 12.6 (latest stable upstream), and additional fixes to the pipelines to unblock builds.
> Update to V8 12.6
