microsoft/v8-jsi

.ado/build-dll.yml
README.md
ReactNative.V8Jsi.Windows.targets
config.json
localbuild.ps1
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h

* delay load the dll by default (so that consumers can have a run-time / optional dependency on v8jsi.dll without needing to distribute it if unused);
* the Platform must be process-singleton to match v8 internals (V8 is not embedder-friendly and makes several assumptions about objects that are initialized once per process - we're matching that design with our V8Platform to avoid crashes if multiple contexts are created / shut down during a process' lifetime);

Delay load v8jsi.dll

---

config.json
localbuild.ps1
scripts/build.ps1
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/V8Platform.cpp
src/V8Platform.h
src/inspector/inspector_agent.cpp
src/jsi/decorator.h
src/jsi/instrumentation.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/test/testlib.cpp

- convert JS errors into C++ jsi::JSError exceptions to match Hermes (for now this covers only function calls);
- update JSI headers to latest available (API compatible, this includes an UTF8 conversion issue fix we found in Office LPC);
- remove some console logging that was leftover from previous implementations;

Convert JS errors into C++ jsi::JSError exceptions; update JSI headers

---

.ado/build-dll.yml
README.md
config.json
scripts/Install-VSFeatures.ps1
scripts/build.ps1
scripts/patch/build.diff
src/BUILD.gn
src/jsi/test/testlib.cpp

14.25 version of the VC tools ignore the FH4- flag. This temporarily pins the VC Tools to 14.24 until we figure out a long-term solution.

Hardcode 14.24 VC tools due to FH4 regression

---

.ado/build-dll.yml
config.json
scripts/patch/build.diff

Now that upstream dependents upgraded form v15 to v16 toolset, we can remove the hardcoded version pinning (which will reduce CI loop time significantly).

Remove FH4-related version pinning

---

ReactNative.V8Jsi.Windows.targets
azure-pipelines.yml
scripts/build.ps1

With UWP and WIN32 in the same NuGet, the resulting nupkg size is ~540Mb, whereas nuget.org has a 250Mb package size limit.
There is support for snupkg (symbol packages) in [nuget](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg), but very little documentation on the Azure DevOps side.
This removed the PDBs from the main v8jsi NuGet, we're still exploring options for where to upload the symbols.

Publish symbols in separate package

---

.ado/build-dll.yml
ReactNative.V8Jsi.Windows.targets
azure-pipelines-uwp.yml
azure-pipelines.yml
config.json
scripts/build.ps1
scripts/fetch_code.ps1

Generate separate packages for win32 and uwp, since together they go over the nuget.org 250Mb limit.

Generate a separate package for UWP

---

.editorconfig
localbuild.ps1
nuget.config
packages.config
scripts/build.ps1
scripts/download_depottools.ps1
scripts/fetch_code.ps1

Use NuGet files to define the version and location of this type of dependencies.
This allows for single-source implicit version dependency management.

Rely on NuGet metadata to manage packages

---

config.json
scripts/patch/src.diff
src/BUILD.gn

Previous commit (update to 8.7) broke the ARM64 build. This cherry-picks [the fix](https://chromium-review.googlesource.com/c/v8/v8/+/2440717) from upstream V8 as a patch.

Fix arm64 build

---

config.json
scripts/patch/src.diff

Replace the custom patch we had for the MSVC debug break on vector custom allocator with cherry-picking the fix in upstream (until we get 9.0): https://chromium-review.googlesource.com/c/v8/v8/+/2622915
V8 8.9 was officially released today, this will rebuild the package with the new commit id from branch head (255.16): https://v8.dev/blog/v8-release-89

Replace custom patch with cherry-pick from V8 9.0 / master

---

config.json
scripts/patch/src.diff

Replace the custom patch we had for the MSVC debug break on vector custom allocator with cherry-picking the fix in upstream (until we get 9.0): https://chromium-review.googlesource.com/c/v8/v8/+/2622915
V8 8.9 was officially released today, this will rebuild the package with the new commit id from branch head (255.16): https://v8.dev/blog/v8-release-89

[0.63] Replace custom patch with cherry-pick from V8 9.0 / master

---

config.json
scripts/patch/src.diff
src/etw/tracing.cpp

V8 9.0 was [released](https://v8.dev/blog/v8-release-90) yesterday; this updates v8jsi to use it.
Also fix unit tests by making sure we don't register the logging providers multiple times.

Update to V8 9.0

---

config.json
src/V8JsiRuntime.cpp

[BabylonReactNative](https://github.com/BabylonJS/BabylonReactNative) uses a [BabylonNative polyfill](https://github.com/BabylonJS/BabylonNative/blob/master/Polyfills/XMLHttpRequest/Source/XMLHttpRequest.cpp#L108) to request a remote resource, and that [uses JSI ArrayBuffer methods](https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/napi/napi-jsi/include/napi/napi-inl.h#L789), which then call into our implementation of the V8 JSI runtime.

Implement ArrayBuffer runtime methods

---

scripts/build.ps1
scripts/patch/src.diff
src/V8JsiRuntime.cpp
src/napi/js_native_ext_api_v8.cpp
src/public/V8JsiRuntime.h

- Disable webassembly support (this shaves 2Mb of the DLL size in x64 release)
- Expose V8 performance tuning flags through the arguments
- Make the flags in V8RuntimeArgs more flexible and resilient to ABI changes (by using a padded struct with some leftover room)

Disable web assembly; add perf tuning flags

---

config.json
src/IsolateData.h
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/inspector/inspector_agent.cpp
src/inspector/inspector_agent.h
src/inspector/inspector_socket_server.cpp
src/inspector/inspector_socket_server.h
src/public/V8JsiRuntime.h

This change has the following effects,
1. API available to open inspector server on an active runtime instance.
2. Ensure that the server management APIs in inspector can be called from any thread.
3. Ensuring the contexts are registered correctly to the inspector. This will correct some issues in multi context runtimes, and when sharing isolates between runtimes, and also result in more symmetric APIs. I don't think we have a multi context/shared-isolate scenario in Office, but having the right model will help us in better reasoning when diagnosing issues.
4. Some improvements in the shutdown flow.

Enable open inspector servers on active runtime instance

---

config.json
scripts/build.ps1
scripts/patch/build.diff
scripts/patch/src.diff
src/V8JsiRuntime.cpp
src/inspector/inspector_agent.cpp
src/public/V8JsiRuntime.h

- revert webassembly disabling which was causing issues with x86 builds (this needs further investigation and follow-up with Google);
- expose debuggerRuntimeName from arguments;

Revert webassembly disabling

---

config.json
scripts/patch/src.diff

dbghelp.dll is only used for symbol resolution if using V8's unhandled exception filter. We don't make much use of that and it makes it harder to port to ARM64EC, so removing the dependency.

Remove the dbghelp dependency

---

config.json
src/inspector/inspector_agent.cpp

1. Fixed the crash when removing the inspector server from the global pool of servers.\
2. Ensure the websocket server and connection is closed when the agent is closed.

Fixing issues when tearing down inspector agent

---

ReactNative.V8Jsi.Windows.targets
config.json

Right now the uwp dlls don't get resolved correctly.
1. The path used always defaults to win32
2. There is no winmd referenced to include the dlls in the build
To fix this, this review adds the following:
1. We set the v8platform to uwp if the application is built with the intention of running in an app container
2. We have the uwp dlls copied to the application output folder so that they get included in the appx

Fix dll resolution for uwp applications

---

config.json
src/BUILD.gn
src/napi/js_native_ext_api_v8.cpp

Add remaining settings for the task runner class:
- `enableInspector`
- `waitForDebugger`
- `foreground_scheduler`
- Required to initialize `foreground_task_runner`
- Depends on #74.
- Must be backported to `0.64-stable` and `0.63-stable`.

Apply NAPI TaskRunner

---

config.json
src/V8JsiRuntime.cpp
src/napi/js_native_ext_api_v8.cpp
src/public/V8JsiRuntime.h
src/public/js_native_ext_api.h

Backport / cherry-pick from master

[0.64-stable] Add a flag for enabling built-in V8 ETW instrumentation

---

config.json
src/V8JsiRuntime.cpp
src/napi/js_native_ext_api_v8.cpp
src/public/V8JsiRuntime.h
src/public/js_native_ext_api.h

Backport / cherry-pick from master

[0.63-stable] Add a flag for enabling built-in V8 ETW instrumentation

---

.ado/android-build.yml
.ado/build-dll.yml

We have a lot of Component Governance (CG) alerts for this repo right now. Most of these appear to be coming from V8 code, which is downloaded at build time. This PR overwrites the auto-injected CG ADO task and adds a manual one that's configured to ignore build\v8build\depot_tools.

Configure Component Governance to ignore build\v8build\depot_tools

---

config.json
scripts/patch/src.diff
src/V8JsiRuntime.cpp

- Update to V8 9.7
- Manually clear the list of HostObjectLifetimeTracker (in case there are leaks at shutdown, to prevent crashing)

Update to V8 9.7

---

config.json
src/V8JsiRuntime.cpp

Use the V8 build number to compose a "runtime signature" for use by the script cache; this would ensure we won't try to load script caches from potentially incompatible V8 builds.

Populate a real runtime signature for PreparedScriptStore

---

config.json
src/inspector/inspector_socket_server.cpp
src/inspector/inspector_socket_server.h
src/testmain.cpp

- Fix the locking code in InspectorSocketServer Start / Stop
- Add unit test for the issue of rapid instance creation / destruction

Add unit tests for Inspector Stop

---

config.json
src/V8JsiRuntime.cpp
src/inspector/inspector_socket_server.cpp
src/inspector/inspector_socket_server.h
src/testmain.cpp

If the runtime is quickly created and torn down with inspector enabled we could end up trying to destroy tcp_server before it finishes creating.
This change protects its creation / destruction with a mutex.

Protect tcp_server access

---

.ado/pull-request.yml

Add step to the CI Build to publish the symbols to http://symweb (internal Microsoft symbol server) to make debugging more pleasant.

Enable Symbol upload to http://symweb

---

.gitignore
README.md
config.json
scripts/fetch_code.ps1
scripts/patch/src.diff
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/public/NapiJsiRuntime.cpp
src/public/compat.h

Google switched to using C++17 for this release, so we can clean up some of the compat code as well (string_view native).

[0.64] Update to V8 9.9

---

android/V8Runtime_impl.h
android/build.config

Added the fix in the V8Runtime enumerator for RN66 - this will unblock the blobs work for Feeds Android

fix: added RN66 blobs fix

---

config.json
scripts/patch/src.diff
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/napi/js_native_ext_api_v8.cpp
src/public/V8JsiRuntime.h
src/public/js_native_ext_api.h

V8 10.0 was released, this brings in the new version.
Also, added a flag to control the size of the threadpool (by default V8 creates max(N-1, 16) with N being the number of cores) - this doesn't break the ABI since we're using the flags_pad space in the arguments.

V8 version bump

---

android/jsi/decorator.h
android/jsi/jsi.h
config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/CMakeLists.txt
src/jsi/JSIDynamic.cpp
src/jsi/JSIDynamic.h
src/jsi/README.md
src/jsi/decorator.h
src/jsi/instrumentation.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/jsilib-posix.cpp
src/jsi/jsilib-windows.cpp
src/jsi/jsilib.h
src/jsi/test/testlib.cpp
src/jsi/test/testlib.h
src/jsi/threadsafe.h
src/public/NapiJsiRuntime.cpp
src/public/NapiJsiRuntime.h

Paired PR to https://github.com/microsoft/hermes-windows/pull/94, 
TDLR: Adds in createPropNameIDFromSymbol to match facebook/hermes JSI
Updated all JSI files to match to https://github.com/facebook/hermes.git
Commit hash:	993a407ec80359e47d2bfac5b17ac533e58e2ed5
Author:		Anand Bashyam <kalyanavarathan@fb.com>#mailto:kalyanavarathan@fb.com
Date:		4/18/2022 10:08:22 AM
A new README.md file is added in the JSI folder about the matching Hermes commit.
Other related changes:
* Fixed HostObjectProxy to work with Symbol PropID and with the prototype chain.
* Formatted code in the changed files.

Adds createPropNameIDFromSymbol

---

config.json
src/BUILD.gn
src/MurmurHash.cpp
src/MurmurHash.h
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h

Since we hardcode the script version to "1" we could get into a state where we're using bytecode / script cache from an older bundle version. This change implements a simple hashing algorithm to version the scripts.
Bonus knowing the script is Ascii lets us skip a copy, and some generic cleanup.

Implement hash for script versioning

---

config.json
src/MurmurHash.cpp
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h

- isAscii was checking only 4 of the 8 bytes;
- update prepareJavaScript / evaluatePreparedJavaScript to use the hashing functionality as well;

Fix isAscii check; use hash in prepareJavaScript

---

config.json
src/MurmurHash.cpp
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h

- isAscii was checking only 4 of the 8 bytes;
- update prepareJavaScript / evaluatePreparedJavaScript to use the hashing functionality as well;

[0.65] Fix isAscii and prepareJavaScript

---

config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/napi/js_native_ext_api_v8.cpp
src/public/NapiJsiRuntime.h
src/public/js_native_ext_api.h

In this PR we add new Node-API extension capability to run JavaScript functions that can use the prepared script store. 
The solution consists of the following parts:
- new function `napi_ext_run_script_buffer` that can run JavaScript from the provided buffer.
- the `napi_ext_env_settings` struct is extended with a new field `script_cache` of type `napi_ext_script_cache`.
- new `napi_ext_script_cache` struct that represents the prepared script store.
- new `napi_ext_cached_script_metadata` struct with JavaScript metadata that used for validating byte code cache.
- new `napi_ext_buffer` struct to represent script text or binary buffer.
- new `napi_ext_native_data` struct as a base type to control lifetime of an external object.
The implementation wraps up the `napi_ext_script_cache` into …

[0.65] Implement PreparedScriptStore for V8 Node-API

---

config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/napi/js_native_ext_api_v8.cpp
src/public/NapiJsiRuntime.h
src/public/js_native_ext_api.h

Cherry pick PR #130:
In this PR we add new Node-API extension capability to run JavaScript functions that can use the prepared script store. 
The solution consists of the following parts:
- new function `napi_ext_run_script_buffer` that can run JavaScript from the provided buffer.
- the `napi_ext_env_settings` struct is extended with a new field `script_cache` of type `napi_ext_script_cache`.
- new `napi_ext_script_cache` struct that represents the prepared script store.
- new `napi_ext_cached_script_metadata` struct with JavaScript metadata that used for validating byte code cache.
- new `napi_ext_buffer` struct to represent script text or binary buffer.
- new `napi_ext_native_data` struct as a base type to control lifetime of an external object.
The implementation wraps up the …

Implement PreparedScriptStore for V8 Node-API

---

config.json
scripts/patch/build.diff
src/V8JsiRuntime.cpp

- Remove the CETCompat flag which causes issues on certain Intel machines
- The stack shouldn't include the message as well. Addresses #136

Remove the CETCompat flag

---

config.json
scripts/patch/build.diff
src/V8JsiRuntime.cpp

- Remove the CETCompat flag which causes issues on certain Intel machines
- The stack shouldn't include the message as well. Addresses #136

[0.65] Remove the CETCompat flag

---

android/build.config
android/jsi/CMakeLists.txt
android/jsi/JSIDynamic.cpp
android/jsi/JSIDynamic.h
android/jsi/decorator.h
android/jsi/instrumentation.h
android/jsi/jsi-inl.h
android/jsi/jsi.cpp
android/jsi/jsi.h
android/jsi/jsilib-posix.cpp
android/jsi/jsilib-windows.cpp
android/jsi/jsilib.h
android/jsi/test/testlib.cpp
android/jsi/test/testlib.h
android/jsi/threadsafe.h

Updated headers for Android with RN68 JSI

patch: updated v8-jsi android with RN68 jsi headers

---

config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/README.md
src/jsi/decorator.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/test/testlib.cpp
src/public/NapiJsiRuntime.cpp

- Created the 0.69-stable branch with the current state, this PR moves the main branch to 0.70;
- Also update V8 version to 10.7;

Update to 0.70 JSI headers

---

scripts/fetch_code.ps1

The folder v8build\v8\third_party\depot_tools\external_bin\gsutil is not used during our builds but is causing Component Governance alerts to get created. This PR adds it to the list of folders we remove during build.

Remove a folder during build to avoid CG alerts.

---

config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/JSIDynamic.cpp
src/jsi/README.md
src/jsi/decorator.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/test/testlib.cpp
src/public/NapiJsiRuntime.cpp

Update the JSI APIs to match version 0.71 of React Native;
The APIs aren't actually implemented in this PR, just stubbed (they're not used in RN yet);

Update to 0.71 JSI API (stubs only)

---

config.json
src/napi/js_native_ext_api_v8.cpp
src/public/js_native_ext_api.h

Currently the Node-API foreground task runner lifetime is depending on the `napi_env` lifetime.
This is wrong because some tasks must be run after the `napi_env` is destroyed.
This issue causes a crash in React Native for Windows when we do direct debugging.
In this PR we are fixing this issue by implementing a new task runner:
- Client code must call `v8_create_task_runner` function to create a new task runner and then pass it to `napi_ext_env_settings` when creating new `napi_env`. The code that internally uses `v8runtime::JSITaskRunner` is responsible for deleting it.
- The `v8_create_task_runner` captures external task scheduler and functions to run tasks and to destroy the external task scheduler.
- This is [a PR in RNW](https://github.com/microsoft/react-native-windows/pull/10966) …

[0.65] Fix task runner for Node-API

---

config.json
scripts/build.ps1
scripts/fetch_code.ps1
scripts/patch/src.diff
src/BUILD.gn

- Update to V8 10.9;
- Disable iterator debugging in debug builds of ARM64 (MSVC compatibility issue);
- Include the toolchain config (needed because we're building with c++17 while V8 / Chromium switched the defaults to c++20 already (JSI code doesn't build in c++20);
- Also fix #156 (use double backslashes for directory separators);

Update to V8 10.9

---

android/V8Runtime_impl.h
android/V8Runtime_shared.cpp
android/build.config
android/jsi/decorator.h
android/jsi/jsi.cpp
android/jsi/jsi.h
android/jsi/jsilib.h
android/jsi/test/testlib.cpp

Bump android jsi to 0.69-stable headers

---

.ado/android-ci.yml

18.04 is no longer a valid ubuntu agent

update ci agent to valid agent

---

android/V8Runtime_impl.h
android/V8Runtime_shared.cpp
android/build.config
android/jsi/decorator.h
android/jsi/jsi-inl.h
android/jsi/jsi.cpp
android/jsi/jsi.h

Bump JSI headers to 0.70-stable and add big int support

Use 0.70 jsi headers

---

android/V8Runtime_impl.h
android/V8Runtime_shared.cpp
android/build.config
android/jsi/JSIDynamic.cpp
android/jsi/decorator.h
android/jsi/jsi-inl.h
android/jsi/jsi.cpp
android/jsi/jsi.h

Upgrade android jsi headers to 0.71-stable

---

scripts/fetch_code.ps1

package.json and package-lock.json under build\v8build\v8\tools are not used during build. We remove them before build to prevent component governance issues.

Remove package.json and package-lock.json before build.

---

config.json
src/napi/js_native_ext_api_v8.cpp
src/public/js_native_ext_api.h

Cherry pick PR #153 to the main branch.
Currently the Node-API foreground task runner lifetime is depending on the `napi_env` lifetime.
This is wrong because some tasks must be run after the `napi_env` is destroyed.
This issue causes a crash in React Native for Windows when we do direct debugging.
In this PR we are fixing this issue by implementing a new task runner:
- Client code must call `v8_create_task_runner` function to create a new task runner and then pass it to `napi_ext_env_settings` when creating new `napi_env`. The code that internally uses `v8runtime::JSITaskRunner` is responsible for deleting it.
- The `v8_create_task_runner` captures external task scheduler and functions to run tasks and to destroy the external task scheduler.
- This is [a PR in …

[0.70] Fix task runner for Node-API (#153)

---

config.json
src/napi/js_native_ext_api_v8.cpp
src/public/js_native_ext_api.h

Cherry pick PR #153 to the main branch.
Currently the Node-API foreground task runner lifetime is depending on the `napi_env` lifetime.
This is wrong because some tasks must be run after the `napi_env` is destroyed.
This issue causes a crash in React Native for Windows when we do direct debugging.
In this PR we are fixing this issue by implementing a new task runner:
- Client code must call `v8_create_task_runner` function to create a new task runner and then pass it to `napi_ext_env_settings` when creating new `napi_env`. The code that internally uses `v8runtime::JSITaskRunner` is responsible for deleting it.
- The `v8_create_task_runner` captures external task scheduler and functions to run tasks and to destroy the external task scheduler.
- This is [a PR in …

Fix task runner for Node-API (#153)

---

config.json
src/napi/js_native_ext_api_v8.cpp
src/public/js_native_ext_api.h

Cherry pick PR #153 to the main branch.
Currently the Node-API foreground task runner lifetime is depending on the `napi_env` lifetime.
This is wrong because some tasks must be run after the `napi_env` is destroyed.
This issue causes a crash in React Native for Windows when we do direct debugging.
In this PR we are fixing this issue by implementing a new task runner:
- Client code must call `v8_create_task_runner` function to create a new task runner and then pass it to `napi_ext_env_settings` when creating new `napi_env`. The code that internally uses `v8runtime::JSITaskRunner` is responsible for deleting it.
- The `v8_create_task_runner` captures external task scheduler and functions to run tasks and to destroy the external task scheduler.
- This is [a PR in …

[0.69] Fix task runner for Node-API (#153)

---

.ado/windows-build.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml

Currently CI pipelines are failing because its image is switched to use VS 2022.
The script cannot find the Google Test Adapter in VS 2019 folder and fails.
In this PR we update the build script to use VS 2022 for PRs and to look for the Google Test Adapter in the VS 2022 folder.
The build job timeout is increased to 5 hours because we see a timeout after 3.5 hours when we build x64 debug for UWP.

Fix CI pipelines

---

.ado/windows-build.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml

Cherry pick PR #171. Original description:
Currently CI pipelines are failing because its image is switched to use VS 2022.
The script cannot find the Google Test Adapter in VS 2019 folder and fails.
In this PR we update the build script to use VS 2022 for PRs and to look for the Google Test Adapter in the VS 2022 folder.
The build job timeout is increased to 5 hours because we see a timeout after 3.5 hours when we build x64 debug for UWP.

[0.65] Fix CI pipelines (#171)

---

.ado/windows-build.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml

Cherry pick PR #171. Original description:
Currently CI pipelines are failing because its image is switched to use VS 2022.
The script cannot find the Google Test Adapter in VS 2019 folder and fails.
In this PR we update the build script to use VS 2022 for PRs and to look for the Google Test Adapter in the VS 2022 folder.
The build job timeout is increased to 5 hours because we see a timeout after 3.5 hours when we build x64 debug for UWP.

[0.70] Fix CI pipelines (#171)

---

src/napi/v8_api.cpp

This PR fixes two issues in the new v8_api.cpp:
- `drainMicrotasks` was returning undefined value
- `tryGetPreparedScript` was retuning non-null even if prepared script is not found in the cache.

Fix v8_api bugs after testing code in applications

---

config.json
src/V8JsiRuntime.cpp

Using the `CompileOptions::kEagerCompile` for the prepared script creation causes crashes in V8 for some scripts.
In this PR we remove this option for the ABI-safe API.
Current non-ABI-safe also does not use this option.
The option worked just fine for the test cases, but it fails for the RN foundation bundle.

Fix prepared script creation

---

config.json
src/inspector/inspector_socket_server.cpp

A recent Edge update (118.0.2088.46) appears to have altered how Chrome Dev Tools request debug targets:
Instead of an HTTP "GET /json/list" request, the dev tools now send "GET /json/list?for_tab". The code change here is intended to alter the URL parser within V8's inspector code to detect the "list" path element when it's being followed by a query URL part.

Update handling of HTTP requests for debug targets

---

README.md
config.json
scripts/patch/build.diff
scripts/patch/src.diff
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/napi/js_native_api_v8.cc

1. Update to V8 version 12.1;
1. Instead of rolling our own script versioning, use the official [CachedDataVersionTag](https://source.chromium.org/chromium/chromium/src/+/main:v8/include/v8-script.h;l=766?q=CachedDataVersionTag&sq=&ss=chromium%2Fchromium%2Fsrc), which hashes additional data like the complete V8 version and compiler flags.

Update to V8 12.1 and improve bytecode versioning

---

.ado/windows-pr.yml
config.json
scripts/fetch_code.ps1
scripts/patch/build.diff
scripts/patch/src.diff
scripts/update_version.ps1
src/V8JsiRuntime.cpp
src/node-api-jsi/NodeApiJsiRuntime.cpp

Populate the beta branch with the Beta version of V8 (12.2). This version included additional checks for isolate entrance/exit consistency which we were failing before, because apparently we kept the Isolated "entered" all the time on the thread.
This change implies that we may create more than one Isolate (even on the same thread) so that's something to look out for (potential perf impact).

[beta] Fixes for 12.2

---

config.json
src/BUILD.gn
src/IsolateData.h
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/JSIDynamic.cpp
src/jsi/JSIDynamic.h
src/jsi/README.md
src/jsi/decorator.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/test/testlib.cpp
src/jsi/test/testlib_ext.cpp
src/node-api-jsi/ApiLoaders/JSRuntimeApi.cpp
src/node-api-jsi/ApiLoaders/JSRuntimeApi.inc
src/node-api-jsi/NodeApiJsiRuntime.cpp
src/node-api/js_runtime_api.h
src/public/V8JsiRuntime.h
src/testmain.cpp

This PR updates the JSI to the latest version.
We assign each JSI change a version and it now corresponds to the version 12.
New methods:
- `queueMicrotask` (version 12)
- `setExternalMemoryPressure` (version 11) (not implemented yet)
This PR also adds implementation of several JSI methods that were not implemented yet:
- `drainMicrotasks` for explicit micro task queue draining when the new `explicitMicrotaskPolicy` argument flag is true.
- `createWeakObject` and `lockWeakObject`
- `createBigIntFromInt64`, `createBigIntFromUint64`, `bigintIsInt64`, `bigintIsUint64`, `bigintToString`
- `hasNativeState`, `getNativeState`, `setNativeState`
- `createArrayBuffer`
New JSI tests to pass:
- MicrotasksTest
- ArrayBufferSizeTest
- NativeState
- NativeStateSymbolOverrides
- UTF8ExceptionTest
New …

Update JSI to version 12

---

config.json
src/jsi/jsi.h

In this change we default JSI version to 11 and change the release version to 0.74.1.
The PR goes to the new `0.74-stable` branch.

[0.74] Implement support for RN 0.74

---

.ado/windows-jobs.yml
config.json

the last publish build had a failure on some of its slices.  But it wasn't setup to cancel the final nuget job if any of the slices failed.  So it attempted to publish a partial nuget.
Unfortunately, retriggers cannot be kicked off, as they would rewrite the build artifacts.
This change should prevent the nuget from attempting to publish unless all the slices complete successfully.

[0.74] Trigger new build, and make publish build more robust to failures

---

.ado/windows-build.yml
.ado/windows-jobs.yml

Moved more parameter handling to ${{ }} syntax which is type checked and handled before the job triggers - rather than during the job execution.
Added some succeeded() checks to the final publish job to ensure it doesn't trigger if the build fails.

More pipeline fixes

---

.ado/windows-ci.yml
.ado/windows-jobs.yml
config.json
src/jsi/jsi.h

This PR backports PR #198 that enables a temporary CI image with 17.8.
It also creates a new release branch 0.71 that is currently used in Office code.
Comparing with the previous release 0.71.14 the new version includes:
- JSI related changes added in PR #190
- Upgrade V8 to  version 12.6 from 12.1 implemented in PR #196

[0.71] Use CI image with VS 17.8 and JSI version 10

---

.ado/windows-jobs.yml

Our Nuget package currently exceeds 500Mb limit set for the ADO feeds.
In this PR we reduce its size by removing support for ARM64 binaries.
Office does not support ARM64 apps. It uses x64 emulation for ARM64.
The change must not affect consumption of V8 in Office.
For other scenarios, we target to restore ARM64 after we switch to the ABI-safe API and stop shipping Debug binaries.

[0.71] Remove support for ARM64

---

.ado/windows-build.yml
.ado/windows-ci.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml
src/jsi/test/testlib_ext.cpp

Previous PR #202 fails in CI because the JSI extended tests `NoCorruptionOnJSError` hangs for x86 Release.
The issue cannot be reproduced locally. Also the CI build takes too much time to complete.
In this PR we:
- Temporary remove the `NoCorruptionOnJSError` test. Also, we increase the test timeout to 5 minutes because we run two sets of JSI tests: v8-jsi and JSI for V8 Node-API.
- Improve the CI build speed by:
- Using less VMs in parallel by combining x64 and x86 builds. The ARM64 takes almost the same time as both x86 and x64 together because it builds ARM64 library and x64 tools.
- Run the SDL checks for source languages such as JS and Python as a part of source analysis instead of repeating them on each CI VM.

[0.71] Disable failing test and improve ci build speed

---

.ado/windows-build.yml
.ado/windows-jobs.yml
ReactNative.V8Jsi.Windows.nuspec
config.json
scripts/patch/build.diff
scripts/patch/src.diff

We are experiencing issues with the v8jsi code after moving to V8 version 12.6.
The V8 compiler crashes in debug mode.
In this PR we:
- Rollback to V8 version 12.1.
- Add back PDB files to the Nuget package since it has smaller size again.
- Change back the build script to use one VM per platform/configuration. It improves the build speed.
- The new v8-jsi package version is set to 0.71.18

[0.71] Revert code to use V8 12.1

---

README.md
config.json
src/V8JsiRuntime.cpp
src/node-api/v8_api.cpp

Cherry pick PR #208 for the 0.71-stable branch. The original description:
Fixed the shutdown sequence for the Node-API based API.
- Rollback all 12.6 related changes in the V8Runtime.
- Delete V8RuntimeEnv instance only after all its Node-API environments are destroyed.
Related changes:
- Some typo fixes in the README.md

[0.74] Fix Node-API based API shutdown sequence

---

README.md
config.json
src/V8JsiRuntime.cpp
src/node-api/v8_api.cpp

Cherry pick PR #208 for the 0.71-stable branch. The original description:
Fixed the shutdown sequence for the Node-API based API.
- Rollback all 12.6 related changes in the V8Runtime.
- Delete V8RuntimeEnv instance only after all its Node-API environments are destroyed.
Related changes:
- Some typo fixes in the README.md

Fix Node-API based API shutdown sequence

---

scripts/fetch_code.ps1

This PR removes several more unused folders prior to the build process to mitigate Component Governance alerts.

Remove more unused code to avoid CG alerts.

---

.ado/windows-build.yml
.ado/windows-ci.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml
.ado/windows-release.yml
config.json
localbuild.ps1
scripts/build.ps1
scripts/download_depottools.ps1
scripts/fetch_code.ps1
scripts/patch/build.diff
scripts/tracing/trace.ps1
scripts/update_version.ps1
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/test/testlib_ext.cpp
src/node-api-jsi/ApiLoaders/V8Api.inc
src/node-api-jsi/NodeApiJsiRuntime.cpp
src/node-api/js_native_api_v8.cc
src/node-api/js_native_api_v8.h
src/node-api/test/node_api_test.cpp
src/node-api/v8_api.cpp
src/public/v8_api.h

We have a new build requirements that all releases must use an YAML-based pipeline.
In this PR we:
- Update version to 0.75.5
- Add new `release.yml` pipeline script.
- Make the `windows-pr.yml` script for PR to follow the recommended settings.
- Convert `windows-jobs.yml` to the base template which is used as a base for `windows-pr.yml` and `windows-ci.yml`.
- Added code sign for DLLs and NuGet packages.
- Added new "FakeBuild" parameter to speed up the pipeline development.
- Report current build info as the build number while running CI and PR pipelines in ADO (`fetch_code.ps1`).
- Add settings recured for secure builds for Debug builds. (`build.diff`)
- Added new `v8_platform_dispose` function to dispose V8 platform. Otherwise, there are random test crashes in Debug caused by GC …

Update build and release pipelines and fix tests

---

.ado/windows-release.yml
config.json
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/CMakeLists.txt
src/jsi/JSIDynamic.cpp
src/jsi/JSIDynamic.h
src/jsi/README.md
src/jsi/decorator.h
src/jsi/instrumentation.h
src/jsi/jsi-inl.h
src/jsi/jsi.cpp
src/jsi/jsi.h
src/jsi/test/testlib.cpp
src/node-api-jsi/NodeApiJsiRuntime.cpp

In the last few months JSI had a number of changes in the Hermes repo.
We assigned a new version to each JSI change commit.
This PR merges changes up to the JSI version 19 and implements new methods in the V8 JSI API and the JSI for Node-API.
The v8-jsi version is changed to 0.79.0 that corresponds to the RN version 0.79 that was still in main when the JSI updates were captured.
Also, this PR fixes the Release pipeline script.

Update JSI to version 19

---

.ado/windows-build.yml
.ado/windows-ci.yml
.ado/windows-jobs.yml
.ado/windows-pr.yml
.ado/windows-release.yml
config.json
localbuild.ps1
scripts/build.ps1
scripts/download_depottools.ps1
scripts/fetch_code.ps1
scripts/patch/build.diff
scripts/tracing/trace.ps1
scripts/update_version.ps1
src/V8JsiRuntime.cpp
src/V8JsiRuntime_impl.h
src/jsi/CMakeLists.txt
src/jsi/test/testlib_ext.cpp
src/node-api-jsi/ApiLoaders/V8Api.inc
src/node-api/js_native_api_v8.cc
src/node-api/js_native_api_v8.h
src/node-api/test/node_api_test.cpp
src/node-api/v8_api.cpp
src/public/v8_api.h

This PR cherry-picks the pipeline and test changes from master to the `0.74-stable` branch: #215, #216.
- Updated version to 0.74.5
- From #216: 
- Add new `windows-release.yml` pipeline script.
- Make the `windows-pr.yml` script for PR to follow the recommended settings.
- Convert `windows-jobs.yml` to the base template which is used as a base for `windows-pr.yml` and `windows-ci.yml`.
- Added code sign for DLLs and NuGet packages.
- Added new "FakeBuild" parameter to speed up the pipeline development.
- Report current build info as the build number while running CI and PR pipelines in ADO (`fetch_code.ps1`).
- Add required settings for secure builds to Debug builds. (`build.diff`)
- Added new `v8_platform_dispose` function to dispose V8 platform. Otherwise, there are random test crashes …

[0.74] Merge pipeline and test changes from master
